<html>
    <head>
        <?php include 'header.php'; ?>

        <title>Restaurant: Locations</title>
    </head>
    <body>
        <h1>Locations</h1>

        <?php include 'aLocation.php'; //remove later these should be generated by another function?>
        <?php
        //db call to get information and number of locations
        require 'shared/dbConnect.php';

        //need js location data to be php session info
        $userLong = 42.5885696;
        $userLat = -71.7914112;
        $sql = "SELECT * FROM `location` ORDER BY ST_Distance_Sphere( point('$userLong' , '$userLat'), point(location.longitude, location.latitude))";
        try {
            $result = queryDb($sql);
            //echo $result(0)(0); //show results  

            //echo "<a class='logLink backLink' href='index.php'>< Home</a>";
        } catch (Exception $e) {
            $error = $e->getMessage();
            echo "Other error: $error \n";
        }


        //js to add info to each
        //https://www.geeksforgeeks.org/program-distance-two-points-earth/
        ?>
        <script>locationElementMaker()</script>
        <!-- https://developers.google.com/maps/documentation/embed/get-started-->
<?php ?>
    </body>
</html>
